CEF.AdminApiApp/Controllers/AppsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Security.Cryptography;
using System.Threading.Tasks;
using CEF.AdminApiApp.Infrastructure;
using CEF.EFAuthJwt.IEF;
using CEF.ServicesAuth.Model;
using CEF.ServicesAuth.Services;
using CEF.Utils.Security;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace CEF.AdminApiApp.Controllers
{
    [Authorize]
    public class AppsController : Controller
    {
        internal IRepositoryWrapper _repo;
        internal ConfigurationTokenJWT _Configuration;

        public AppsController(IRepositoryWrapper Repo, ConfigurationTokenJWT Configuration)
        {
            _repo = Repo;
            _Configuration = Configuration;


        }
        public async Task<IActionResult> Index()
        {
            List<AppToken> ObjApps =await new ApplicationKey(_repo).GetApps();
            return View(ObjApps);
        }
        public async Task<IActionResult> Edit(int Id)
        {
            AppToken ObjApp = new AppToken();
            ObjApp = await new ApplicationKey(_repo).GetTokenFromAppKey(Id);
            return View(ObjApp);
        }
        //public async Task<IActionResult> Edit(int Id)
        //{
        //    AppToken ObjApp = new AppToken();
        //    ObjApp = await new ApplicationKey(_repo).GetTokenFromAppKey(Id);
        //    return View(ObjApp);
        //}
         
        [ValidateAntiForgeryToken]
        [HttpPost]
       
        public async Task<IActionResult> Save(AppToken oApp,string appsAcction)
        {
            if (appsAcction== "Generar Token")
            {
                AppToken ObjApp = oApp;
                var claims = new List<Claim>
                        {
                        new Claim(ClaimTypes.Name, ObjApp.Name )
                        };
                        claims.Add(new Claim(ClaimTypes.NameIdentifier, ObjApp.IdApp.ToString()));
                        claims.Add(new Claim(ClaimTypes.Role, AppRoles.Read));
                        string token = UtilyJwt.GenerateTokenJwt(ObjApp.Name, _Configuration.JWT_SECRET_KEY, _Configuration.JWT_AUDIENCE_TOKEN,
                                _Configuration.JWT_ISSUER_TOKEN, _Configuration.JWT_EXPIRE_MINUTES, claims);
                        ObjApp.Token = token;
                await new ApplicationKey(_repo).SaveTokenToApp(ObjApp);
            }
            else if (appsAcction == "Close")
            {
                return RedirectToAction("Index", new {  });
            }
            else
            { 
            
                if (oApp.IdApp ==0)
                {
                    AppToken ObjApp = oApp;
                    var key = new byte[32];
                    using (var generator = RandomNumberGenerator.Create())
                    generator.GetBytes(key);
                    string apiKey = Convert.ToBase64String(key);
                    var claims = new List<Claim>
                        {
                        new Claim(ClaimTypes.Name, ObjApp.Name )
                        };
                        claims.Add(new Claim(ClaimTypes.NameIdentifier, ObjApp.IdApp.ToString()));
                        claims.Add(new Claim(ClaimTypes.Role, AppRoles.Read));
                        string token = UtilyJwt.GenerateTokenJwt(ObjApp.Name, _Configuration.JWT_SECRET_KEY, _Configuration.JWT_AUDIENCE_TOKEN,
                                _Configuration.JWT_ISSUER_TOKEN, _Configuration.JWT_EXPIRE_MINUTES, claims);
                        ObjApp.Token = token;
                        ObjApp.Code = apiKey;
                        await new ApplicationKey(_repo).SaveTokenToApp(ObjApp);
                        oApp.IdApp= ObjApp.IdApp;
                        oApp.Token = ObjApp.Token;


                }
                else
                {
                    AppToken ObjApp = await new ApplicationKey(_repo).GetTokenFromAppKey(oApp.IdApp );
                    ObjApp.Actived = oApp.Actived;
                    ObjApp.IdApp = oApp.IdApp;
                    ObjApp.Name = oApp.Name;
                    
                    await new ApplicationKey(_repo).SaveTokenToApp(ObjApp);


                }
            }
            return RedirectToAction("Edit",new { Id = oApp.IdApp });
        }
    }
}

CEF.AdminApiApp/Controllers/LoginController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using CEF.AdminApiApp.Infrastructure;
using CEF.AdminApiApp.Models;
using CEF.EFAuthJwt.IEF;
using CEF.ServicesAppAdminApi.Model;
using CEF.ServicesAppAdminApi.Services;
using CEF.Utils.Security;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Primitives;

namespace CEF.AdminApiApp.Controllers
{
    public class LoginController : Controller
    {
        internal IRepositoryWrapper _repo;
        internal ConfigurationTokenJWT _Configuration;

        public LoginController(IRepositoryWrapper Repo, ConfigurationTokenJWT Configuration)
        {
            _repo = Repo;
            _Configuration = Configuration;


        }
        public async Task<IActionResult> Index()
        {
            LoginModel ObjLogin = new LoginModel();
             
            return View(ObjLogin);
        }
        public async Task<IActionResult> Logout()
        {
            HttpContext.Session.Clear();
            await HttpContext.SignOutAsync(CookieAuthenticationDefaults.AuthenticationScheme);

            return RedirectToAction ("Index");
        }
       
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Index(LoginModel ObjLogin)
        {
            try
            {
                if(await  new Users(_repo).VerifyUser(ObjLogin.User , ObjLogin.Password))
                {
                  UserApp ObjUsuario= await  new Users(_repo).GetUserByUserName(ObjLogin.User);
                    var claims = new List<Claim>
                    {
                    new Claim(ClaimTypes.Name, ObjLogin.User )
                    };
                    if (ObjUsuario == null)
                    {
                        ModelState.AddModelError("", "username or password is invalid");
                    }
                    else
                    {

                        claims.Add(new Claim("hasAccess","true"));
                        //claims.Add(new Claim(ClaimTypes.Role, CustomRoles.Admin));
                        claims.Add(new Claim(ClaimTypes.NameIdentifier, ObjUsuario.Id.ToString()));
                        string token = UtilyJwt.GenerateTokenJwt(ObjUsuario.Name, _Configuration.JWT_SECRET_KEY, _Configuration.JWT_AUDIENCE_TOKEN,
                            _Configuration.JWT_ISSUER_TOKEN, _Configuration.JWT_EXPIRE_MINUTES, claims);
                        claims.Add(new Claim("access_token", token));
                        var userIdentity = new ClaimsIdentity(claims, CookieAuthenticationDefaults.AuthenticationScheme);

                        ClaimsPrincipal principal = new ClaimsPrincipal(userIdentity);
                        var authticationProperties = new AuthenticationProperties();

                        await HttpContext.SignInAsync(
                          CookieAuthenticationDefaults.AuthenticationScheme,
                          new ClaimsPrincipal(userIdentity),
                          authticationProperties);

                        HttpContext.Session.SetString("JWToken", token);

                        

                            return RedirectToAction ("Index","Home");
                        


                    }
                }
                else
                {
                    ModelState.AddModelError("", "Usuario o Clave Incorrectos");
                }
                return View(  ObjLogin);
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", ex.Message.ToString()+" "+ _Configuration.ConnectionStringDB);
                return View();
            }
        }

    }
}

CEF.AdminApiApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"]- Portal Gestión Accesos Api CEFp</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute"
              crossorigin="anonymous"
              integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" />
    </environment>
    <link rel="stylesheet" href="~/css/site.css" />
    <script src="https://code.jquery.com/ui/1.12.0/jquery-ui.js"
            integrity="sha256-0YPKAwZP7Mp3ALMRVB2i8GXeEndvCq3eSl/WsAl1Ryk="
            crossorigin="anonymous"></script>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Portal Gestión Accesos Api CEF</a>

                @if (User.Identity.IsAuthenticated)
                {
                    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                            aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">


                        <ul class="navbar-nav flex-grow-1">
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Inicio</a>

                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Apps" asp-action="Index">Apps Access</a>

                            </li>

                        </ul>

                    </div>
                }
                @if (User.Identity.IsAuthenticated)
                {

                    <text> Usuario </text> <a class="username" style="margin-left:5px;" href="/user?id=@User.Claims.First(x => x.Type == System.Security.Claims.ClaimTypes.NameIdentifier).Value">@User.Identity.Name</a>

                    @using (Html.BeginForm("Logout", "Login", FormMethod.Get))
                    {
                        <span class="nav-item" style="float:right;margin-left:10px;">
                            @Html.AntiForgeryToken()

                            <button class="btn btn-outline-warning my-2 my-sm-0" type="submit" asp-area="" asp-controller="Login" asp-action="Logout">Salir</button>
                        </span>
                    }


                }
                else
                {


                    <span class="nav-item">
                        <button class="btn btn-outline-success my-2 my-sm-0" type="submit" asp-area="" asp-controller="Home" asp-action="Index">Acceso</button>
                    </span>

                }
            </div>
        </nav>
    </header>
    <div class="container">
        <partial name="_CookieConsentPartial" />
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - CEF.AdminApiApp - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.js"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=">
        </script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.bundle.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-xrRywqdh3PHs8keKZN+8zzc5TX0GRTLCcmivcbNJWm2rs5C8PRhcEn3czEjhAO9o">
        </script>
    </environment>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>